import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lexend_Deca } from "next/font/google";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";





const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={inter.variable}>
      <body
      
      >
        <Navbar/>
   {children}

       
      </body>
    </html>
  );
}
