const villages = [
     { value: "selectAll", label: "Select All" },
    { value: "Solferino", label: "Solferino" },
    { value: "Terre rouge", label: "Terre rouge" },
    { value: "Phoenix", label: "Phoenix" },
    { value: "Trianon", label: "Trianon" },
    { value: "Grand bois", label: "Grand bois" },
    { value: "Beau bassin", label: "Beau bassin" },
    { value: "Quatre bornes", label: "Quatre bornes" },
    { value: "Forest - side", label: "Forest - side" },
    { value: "Rose- hill", label: "Rose- hill" },
    { value: "Port louis", label: "Port louis" },
    { value: "Montagne blanche", label: "Montagne blanche" },
    { value: "Rodrigues - grand montagne", label: "Rodrigues - grand montagne" },
    { value: "Rodrigues - port mathurin", label: "Rodrigues - port mathurin" },
    { value: "Rodrigues - la ferme", label: "Rodrigues - la ferme" },
    { value: "Rodrigues - mont lubin", label: "Rodrigues - mont lubin" },
    { value: "Rodrigues - riviere coco", label: "Rodrigues - riviere coco" },
    { value: "Agalega", label: "Agalega" },
    { value: "Vacoas / floreal", label: "Vacoas / floreal" },
    { value: "Verdun", label: "Verdun" },
    { value: "Ville bague", label: "Ville bague" },
    { value: "Union park", label: "Union park" },
    { value: "Union ducray / st aubin", label: "Union ducray / st aubin" },
    { value: "Trois boutiques", label: "Trois boutiques" },
    { value: "The vale", label: "The vale" },
    { value: "Trou aux biches", label: "Trou aux biches" },
    { value: "Tombeau bay", label: "Tombeau bay" },
    { value: "Tamarin", label: "Tamarin" },
    { value: "Trou d'eau douce", label: "Trou d'eau douce" },
    { value: "Triolet", label: "Triolet" },
    { value: "Tyack", label: "Tyack" },
    { value: "Saint pierre", label: "Saint pierre" },
    { value: "Saint julien village", label: "Saint julien village" },
    { value: "Sebastopol", label: "Sebastopol" },
    { value: "Surinam", label: "Surinam" },
    { value: "St hubert", label: "St hubert" },
    { value: "Saint julien d'hotman", label: "Saint julien d'hotman" },
    { value: "Souillac", label: "Souillac" },
    { value: "Reduit", label: "Reduit" },
    { value: "Rose belle", label: "Rose belle" },
    { value: "Riviere du rempart", label: "Riviere du rempart" },
    { value: "Ripailles", label: "Ripailles" },
    { value: "Riviere des creoles", label: "Riviere des creoles" },
    { value: "Riviere des anguilles", label: "Riviere des anguilles" },
    { value: "Riviere du poste", label: "Riviere du poste" },
    { value: "Roche terre", label: "Roche terre" },
    { value: "Richelieu", label: "Richelieu" },
    { value: "Roches noires", label: "Roches noires" },
    { value: "Quatre soeurs", label: "Quatre soeurs" },
    { value: "Queen victoria", label: "Queen victoria" },
    { value: "Quatre cocos", label: "Quatre cocos" },
    { value: "Quartier militaire", label: "Quartier militaire" },
    { value: "Pointe aux sables", label: "Pointe aux sables" },
    { value: "Petit bel air", label: "Petit bel air" },
    { value: "Pamplemousses", label: "Pamplemousses" },
    { value: "Plaine magnien", label: "Plaine magnien" },
    { value: "Poudre d'or village", label: "Poudre d'or village" },
    { value: "Poudre d'or hamlet", label: "Poudre d'or hamlet" },
    { value: "Pointe aux piments", label: "Pointe aux piments" },
    { value: "Providence", label: "Providence" },
    { value: "Petit raffray", label: "Petit raffray" },
    { value: "Plaine des papayes", label: "Plaine des papayes" },
    { value: "Piton", label: "Piton" },
    { value: "Petite riviere", label: "Petite riviere" },
    { value: "Gros cailloux", label: "Gros cailloux" },
    { value: "Poste de flacq", label: "Poste de flacq" },
    { value: "Olivia", label: "Olivia" },
    { value: "Old grand port", label: "Old grand port" },
    { value: "Nouvelle decouverte", label: "Nouvelle decouverte" },
    { value: "Notre dame", label: "Notre dame" },
    { value: "Nouvelle france", label: "Nouvelle france" },
    { value: "New grove", label: "New grove" },
    { value: "Moka", label: "Moka" },
    { value: "Midlands", label: "Midlands" },
    { value: "Mare tabac", label: "Mare tabac" },
    { value: "Mare la chaux", label: "Mare la chaux" },
    { value: "Mapou", label: "Mapou" },
    { value: "Mahebourg", label: "Mahebourg" },
    { value: "Mare d'albert", label: "Mare d'albert" },
    { value: "Morc st andre", label: "Morc st andre" },
    { value: "Medine camp de masque", label: "Medine camp de masque" },
    { value: "Melrose", label: "Melrose" },
    { value: "La laura / malenga", label: "La laura / malenga" },
    { value: "L'avenir", label: "L'avenir" },
    { value: "Long mountain", label: "Long mountain" },
    { value: "L'escalier", label: "L'escalier" },
    { value: "L'esperance trebuchet", label: "L'esperance trebuchet" },
    { value: "Laventure", label: "Laventure" },
    { value: "Le morne", label: "Le morne" },
    { value: "La gaulette", label: "La gaulette" },
    { value: "Le hochet", label: "Le hochet" },
    { value: "L'esperance", label: "L'esperance" },
    { value: "Lalmatie", label: "Lalmatie" },
    { value: "La flora", label: "La flora" },
    { value: "G.r.s.e", label: "G.r.s.e" },
    { value: "Grand bel air", label: "Grand bel air" },
    { value: "Goodlands", label: "Goodlands" },
    { value: "Grand sable", label: "Grand sable" },
    { value: "Grand bay", label: "Grand bay" },
    { value: "Grand gaube", label: "Grand gaube" },
    { value: "Grande retraite", label: "Grande retraite" },
    { value: "16eme mille", label: "16eme mille" },
    { value: "Fond du sac", label: "Fond du sac" },
    { value: "Flic en flac", label: "Flic en flac" },
    { value: "Eau coulee", label: "Eau coulee" },
    { value: "Ebene", label: "Ebene" },
    { value: "Ecroignard", label: "Ecroignard" },
    { value: "Dagotiere", label: "Dagotiere" },
    { value: "Dubreuil", label: "Dubreuil" },
    { value: "D'epinay", label: "D'epinay" },
    { value: "Curepipe", label: "Curepipe" },
    { value: "Clemencia", label: "Clemencia" },
    { value: "Camp ithier", label: "Camp ithier" },
    { value: "Cascavelle", label: "Cascavelle" },
    { value: "Congomah", label: "Congomah" },
    { value: "Creve coeur", label: "Creve coeur" },
    { value: "Calebasses", label: "Calebasses" },
    { value: "Camp carol", label: "Camp carol" },
    { value: "Chamouny", label: "Chamouny" },
    { value: "Cluny", label: "Cluny" },
    { value: "Cottage", label: "Cottage" },
    { value: "Camp diable", label: "Camp diable" },
    { value: "Central flacq", label: "Central flacq" },
    { value: "Chamarel", label: "Chamarel" },
    { value: "Case noyale", label: "Case noyale" },
    { value: "Chemin grenier", label: "Chemin grenier" },
    { value: "Cap malheureux", label: "Cap malheureux" },
    { value: "Camp de masque pave", label: "Camp de masque pave" },
    { value: "Camp de masque", label: "Camp de masque" },
    { value: "Brisee verdiere", label: "Brisee verdiere" },
    { value: "Bel air", label: "Bel air" },
    { value: "Bramsthan", label: "Bramsthan" },
    { value: "Bambous", label: "Bambous" },
    { value: "Beau vallon", label: "Beau vallon" },
    { value: "Black river", label: "Black river" },
    { value: "Bananes", label: "Bananes" },
    { value: "Bel ombre", label: "Bel ombre" },
    { value: "Baie du cap", label: "Baie du cap" },
    { value: "Britannia", label: "Britannia" },
    { value: "Benares", label: "Benares" },
    { value: "Bambous virieux", label: "Bambous virieux" },
    { value: "Bois des amourettes", label: "Bois des amourettes" },
    { value: "Bois cheri", label: "Bois cheri" },
    { value: "Bon accueil", label: "Bon accueil" },
    { value: "Arsenal", label: "Arsenal" },
    { value: "Amitie gokhoola", label: "Amitie gokhoola" },
    { value: "Albion", label: "Albion" },
  
  ];

  export default villages;